image: alpine:latest

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - business-card
  publish: business-card  # Specify the folder to use for Pages
  only:
    - main